services:
  app:
    build: .
    environment:
      - CH_CONN_STRING
      - TZ
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

#  db:
#    image: clickhouse/clickhouse-server:latest
#    ports:
#      - "8123:8123"
#      - "9000:9000"
#    volumes:
#      - clickhouse_data:/var/lib/clickhouse
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
#    healthcheck:
#      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
#      interval: 5s
#      timeout: 5s
#      retries: 5
#    restart: unless-stopped
#
#volumes:
#  clickhouse_data:
